// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4LD08UnrFUBzs2WrDl3KYnsMWK3u3e9c',
    appId: '1:92708996157:web:1f06b378f57c6890c49654',
    messagingSenderId: '92708996157',
    projectId: 'jazzee-9b074',
    authDomain: 'jazzee-9b074.firebaseapp.com',
    storageBucket: 'jazzee-9b074.appspot.com',
    measurementId: 'G-R9L1YZLETN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1xoyVfV9JJG-3FhW8cGjAgmAEk_M4Lc',
    appId: '1:92708996157:android:d42d7b4eed1e0ab3c49654',
    messagingSenderId: '92708996157',
    projectId: 'jazzee-9b074',
    storageBucket: 'jazzee-9b074.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSxEUNv1z8cXTQ5XW1c96H5RBGerinyew',
    appId: '1:92708996157:ios:ec6052b540b60c84c49654',
    messagingSenderId: '92708996157',
    projectId: 'jazzee-9b074',
    storageBucket: 'jazzee-9b074.appspot.com',
    iosBundleId: 'com.example.jazzee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSxEUNv1z8cXTQ5XW1c96H5RBGerinyew',
    appId: '1:92708996157:ios:ec6052b540b60c84c49654',
    messagingSenderId: '92708996157',
    projectId: 'jazzee-9b074',
    storageBucket: 'jazzee-9b074.appspot.com',
    iosBundleId: 'com.example.jazzee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4LD08UnrFUBzs2WrDl3KYnsMWK3u3e9c',
    appId: '1:92708996157:web:0acc587df8937e1cc49654',
    messagingSenderId: '92708996157',
    projectId: 'jazzee-9b074',
    authDomain: 'jazzee-9b074.firebaseapp.com',
    storageBucket: 'jazzee-9b074.appspot.com',
    measurementId: 'G-ZQEXV87T3H',
  );
}
